-- phpMyAdmin SQL Dump
-- version 2.11.11.3
-- http://www.phpmyadmin.net
--
-- Host: 50.63.107.163
-- Generation Time: Oct 22, 2012 at 08:53 PM
-- Server version: 5.0.92
-- PHP Version: 5.1.6

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `charitynavigator`
--

-- --------------------------------------------------------

--
-- Table structure for table `list`
--

CREATE TABLE `list` (
  `listid` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `updated` datetime NOT NULL,
  `version` int(11) NOT NULL,
  `typeid` int(11) NOT NULL,
  `list_type` varchar(64) NOT NULL,
  `resource_uri` text NOT NULL,
  `listname` varchar(100) NOT NULL,
  `description` text NOT NULL,
  PRIMARY KEY  (`listid`),
  KEY `listname` (`listname`),
  KEY `list_type` (`list_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `list`
--

INSERT INTO `list` VALUES(7, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/7/', '10 Charities Worth Watching', 'Many of America''s most effective charities are also household names.  But some well-known charities are less effective than you''d think, while a number of lesser known charities are truly exceptional.  These 10 charities all <b>operate on less than $2 million a year</b>, but they all earn a four-star rating from Charity Navigator.  We encourage you to learn more about them.');
INSERT INTO `list` VALUES(8, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/8/', '10 Highly Paid CEOs at Low-Rated Charities', 'For charities to be successful, they need talented, experienced leaders. Those leaders command significant salaries. But CEOs who command high salaries should also get the most out of the organizations they lead. The leaders of these 10 organizations are taking high salaries at the expense of spending dollars on the charity''s programs. Despite receiving more than $200,000 in annual pay, these CEOs run organizations that devote <b>less than 60% of their budgets to their programs and services</b>. That means that at least 40% of your dollars are going to such costs as fundraising and administration, including the salary of the CEO.');
INSERT INTO `list` VALUES(10, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/10/', '10 Inefficient Fundraisers', 'Excellent charities succeed because their resources are not tied up in fundraising.  They find creative ways to spend less to raise more, thereby maximizing the resources they can devote to their programs.  These 10 charities are not so fortunate or efficient.  They spend more than $0.50 to raise each dollar in support, making them four times less efficient than the average charity.  This inefficiency forces them to <b>devote more than 40% of their budgets to fundraising</b>, limiting the difference they can make with your dollars.');
INSERT INTO `list` VALUES(11, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/11/', '10 Charities Expanding in a Hurry', 'Expect to hear about these 10 charities long into the future.  They are growing dramatically.  Over the past three years, these charities <b>have grown their primary sources of revenue by more than 35% each year</b>.  Over that same period, they have expanded their programs and services by more than 35% each year.  In addition, these <b>organizations also have enough money in the bank</b> to sustain a similar rate of growth for years to come.');
INSERT INTO `list` VALUES(12, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/12/', '10 Charities in Deep Financial Trouble', 'If an organization owes more than it owns, that''s a bad sign.  If the bills it owes by the end of the year are more than it can pay, that''s an even worse sign.  <b>These 10 charities are insolvent.</b> Not only do their<b> total liabilities, or what they owe, exceed their total assets</b>,  they also maintain negative working capital -- that is, the bills they owe exceed available assets that can be used to pay those bills.  While these charities may not be facing bankruptcy, their fundamental insolvency puts these charities in a very dangerous position.');
INSERT INTO `list` VALUES(15, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/15/', '10 Most Frequently Viewed Charities', 'Popularity doesn''t make a charity more effective or more worthy of support. But it does show that people know your name. These 10 charities are the most frequently visited on our web site. They are <b>ranked by number of page views in the past 30 days.</b>');
INSERT INTO `list` VALUES(16, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/16/', '10 Charities Routinely in the Red', 'Outspending your means can set a dangerous precedent. <b>These 10 charities have run deficits in each of their last 3 fiscal years, establishing a pattern of overspending</b>. They are <b>ranked by the ratio of their average deficit to their average total expenses</b>. This ratio conveys how significant the deficit is for each charity.');
INSERT INTO `list` VALUES(17, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/17/', '10 Highly Rated Charities Relying on Private Contributions', 'Most charities derive large chunks of revenue from earned income, membership fees, and government contracts and grants. <b>Ranked by overall score, these 10 excellent charities draw revenue solely from direct and indirect public support</b>. They report no government funding, no membership fees, and no revenue from earned income. \r\nAs a result, <b>more than 95% of their total revenue comes from private contributions</b>, which makes the efficiency of their fundraising operations all the more impressive.');
INSERT INTO `list` VALUES(18, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/18/', '10 of the Best Charities Everyone''s Heard Of', 'These 10 charities work throughout the country and the world. They are large, complex organizations with budgets exceeding $100 million, and at least $65 million in net assets. They became household names in part because of their exceptional financial management, no easy feat considering the scope and size of their operations. Charitable givers should feel confident that these national institutions put their donations to good use.');
INSERT INTO `list` VALUES(22, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/22/', '10 Celebrity-Related Charities', 'Celebrity endorsements help charities increase awareness of their endeavors and thus stimulate more donations. However, just because your favorite super-star supports a charity doesn''t mean the charity is well-run and worthy of a contribution from you. Check out how we rate these 10 charities which are closely aligned, in some cases even named for, the celebrities that founded or support them.');
INSERT INTO `list` VALUES(24, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/24/', '10 Super-Sized Charities', 'This Top 10 list contains some heavy hitters in the nonprofit sector. Each of these charities had total expenses greater than $500 million in its most recent fiscal year. Their combined total expenses are approximately $10 billion. We offer this list because we believe it is enlightening for donors to realize just how large many of America''s charities are and why we believe it is important that our country establish a federal regulatory agency to monitor and regulate charities.');
INSERT INTO `list` VALUES(28, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/28/', '10 Charities Overpaying their For-Profit Fundraisers', 'These 10 charities are not living up to their missions. Each spends more than 50% of its budget paying for-profit fundraising professionals to solicit your hard-earned money. They are ranked by the percentage of their total functional expenses spent on professional fundraising fees. As a result, very little of the charity''s spending is directed towards its programs and services.');
INSERT INTO `list` VALUES(88, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/88/', 'Hurricane Ike', '');
INSERT INTO `list` VALUES(92, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/92/', '10 Highly-Rated Charities with Low Paid CEOs', 'The leaders of these 10 organizations run highly-rated charities, yet they earn far less than the average compensation of $150,000 reported by the over 5,000 charities rated by Charity Navigator. The low salaries help these charities, which have earned at least two consecutive 4-star ratings, devote more than 80% of their budgets to their programs and services. That means that less than 20% of your dollars are going to such costs as fundraising and administration, including the salary of the CEO. The list is ranked by the CEO''s compensation.');
INSERT INTO `list` VALUES(100, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/100/', '10 Charities with the Most Consecutive 4-Star Ratings', 'Charities tackle some of society’s most complex and intractable issues --- such as combating hunger, preserving the environment, curing diseases and changing people’s perceptions. These are long-term objectives. To be successful, organizations must be high performers consistently, year after year. These ten charities have earned the most consecutive 4-star ratings demonstrating an ongoing fiscal excellence. They are well-positioned to pursue and achieve long-term change.');
INSERT INTO `list` VALUES(106, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/106/', 'Earthquake in Haiti', '');
INSERT INTO `list` VALUES(107, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/107/', 'New Ratings Funded by the Hobbs Foundation', '2010 list, index.cfm?bay=content.view&cpid=1013');
INSERT INTO `list` VALUES(112, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/112/', 'Charities Providing Relief', '');
INSERT INTO `list` VALUES(113, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/113/', '10 Top-Notch Charities', 'At Charity Navigator we believe that high-performing charities excel in three areas: (1) financial, (2) accountability & transparency and (3)  results. We expanded our rating system in September 2011 from one that solely looked at financial indicators to one that also includes metrics of accountability & transparency. These ten charities not only earn our highest 4-star rating for their Financial Health, but they also earn 4-stars in Accountability & Transparency.  This tells us that these 10 charities adhere to good governance and other best practices that minimize the chance of unethical activities and that they execute their missions in a fiscally responsible way.');
INSERT INTO `list` VALUES(115, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/115/', '10 Charities with the Most Consecutive 4-Star Ratings (Excluding Universities)', 'Charities tackle some of society’s most complex and intractable issues --- such as combating hunger, preserving the environment, curing diseases and changing people’s perceptions. These are long-term objectives. To be successful, organizations must be high performers consistently, year after year. These ten charities have earned the most consecutive 4-star ratings demonstrating an ongoing fiscal excellence. They are well-positioned to pursue and achieve long-term change.');
INSERT INTO `list` VALUES(118, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/118/', '10 Highly Rated Charities with Favorable Reviews', 'Each of these 10 charities has been vetted by Charity Navigator and by the public. They’ve all earned the highest, 4-star rating from Charity Navigator. And these charities also have the highest average review rating (and a minimum of 10 reviews) from various stakeholders (such as donors, recipients of the charity’s services, volunteers and community partners). The reviews are powered  by our partner GreatNonprofits.\r\n\r\nVisit the charity’s ratings page to see their Charity Navigator rating and then click on the ''Reviews'' tab to see what others had to say about their personal experience with the charity. From there you can also submit your own review.');
INSERT INTO `list` VALUES(120, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/120/', 'Japan Earthquake and Tsunami', '');
INSERT INTO `list` VALUES(125, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/125/', '10 Well Known Charities without Reviews', 'Each of these 10 charities is large and relatively well-known. Still they do not have a single stakeholder review. You can help them get off this list by writing a review now. Just click on the charity’s name to go to the organization''s ratings page. From there, click on the "Reviews" tab, powered by our partner GreatNonprofits, which will enable you to share your personal story with the charity so that other donors can benefit by knowing of your experience.');
INSERT INTO `list` VALUES(127, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/127/', 'Crisis in East Africa', '');
INSERT INTO `list` VALUES(146, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/146/', 'New Ratings Sponsored by the Hobbs Foundation', '');
INSERT INTO `list` VALUES(147, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/147/', '10 All Time Most Popular Charity Ratings', 'In celebration of Charity Navigator’s 10th Anniversary (April 2012), we thought it would be interesting to take a look back and see which charities’ ratings have been the most popular over the years. Among the more than 5,000 charities we rate, the following 10 charities’ ratings pages have received the most visits. They are ranked by number of page views from August 2006 (when we began tracking pageviews) through March 2012. \r\n<p>Of these 10 charities, just 4 were among the approximately 1,100 we rated when we launched our site on April 15, 2002. Those 4 are: World Vision, Doctors Without Borders, USA, Save the Children and Feed The Children.</p>\r\n<p><em>Remember, popularity  doesn''t make a charity more effective or more worthy of your support.</em> </p>');
INSERT INTO `list` VALUES(148, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 1, 'Top Ten', 'http://api.charitynavigator.org/api/v1/lists/148/', '10 Most Followed Charities', 'Since Charity Navigator launched in 2002, hundreds of thousands of donors that have become registered users of our site. Registered users have access to (free) premier tools on our site including the ability to share a list of charities, compare charities, view historical data and subscribe to our monthly, email newsletter.  Registered users can also create personal portfolios of charities to track the performance of their favorite charities overtime. The 10 charities that have been most frequently added to registered users’ portfolios are listed below. They are ranked by the number of portfolios that include them.');
INSERT INTO `list` VALUES(151, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/151/', 'Olympic and Sports Related Charities', '');
INSERT INTO `list` VALUES(152, '2012-10-20 06:01:33', '2012-10-20 06:01:33', 1, 2, 'Article', 'http://api.charitynavigator.org/api/v1/lists/152/', 'Hurricane Isaac', '');
